// <auto-generated />
using System;
using WorkflowTracking.Modules.Users.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace WorkflowTracking.Modules.Users.Infrastructure.Database.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("users")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorkflowTracking.Common.Infrastructure.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "users");
                });

            modelBuilder.Entity("WorkflowTracking.Common.Infrastructure.Inbox.InboxMessageConsumer", b =>
                {
                    b.Property<Guid>("InboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("InboxMessageId", "Name")
                        .HasName("pk_inbox_message_consumers");

                    b.ToTable("inbox_message_consumers", "users");
                });

            modelBuilder.Entity("WorkflowTracking.Common.Infrastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", "users");
                });

            modelBuilder.Entity("WorkflowTracking.Common.Infrastructure.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.HasKey("OutboxMessageId", "Name")
                        .HasName("pk_outbox_message_consumers");

                    b.ToTable("outbox_message_consumers", "users");
                });

            modelBuilder.Entity("WorkflowTracking.Modules.Users.Domain.Invitations.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClassroomId")
                        .HasMaxLength(200)
                        .HasColumnType("uuid")
                        .HasColumnName("classroom_id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("mobile");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_invitations");

                    b.ToTable("invitations", "users");
                });

            modelBuilder.Entity("WorkflowTracking.Modules.Users.Domain.Users.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", "users");

                    b.HasData(
                        new
                        {
                            Code = "users:read"
                        },
                        new
                        {
                            Code = "users:create"
                        },
                        new
                        {
                            Code = "users:update"
                        },
                        new
                        {
                            Code = "classrooms:read"
                        },
                        new
                        {
                            Code = "classrooms:create"
                        },
                        new
                        {
                            Code = "classrooms:update"
                        },
                        new
                        {
                            Code = "classrooms:delete"
                        },
                        new
                        {
                            Code = "classrooms:add-student"
                        },
                        new
                        {
                            Code = "classrooms:remove-student"
                        },
                        new
                        {
                            Code = "students:invite"
                        },
                        new
                        {
                            Code = "attendance:read"
                        },
                        new
                        {
                            Code = "attendance:record"
                        },
                        new
                        {
                            Code = "attendance:update"
                        },
                        new
                        {
                            Code = "qr:generate"
                        },
                        new
                        {
                            Code = "qr:scan"
                        },
                        new
                        {
                            Code = "spiritual:read"
                        },
                        new
                        {
                            Code = "spiritual:record"
                        },
                        new
                        {
                            Code = "roles:read"
                        },
                        new
                        {
                            Code = "roles:update"
                        });
                });

            modelBuilder.Entity("WorkflowTracking.Modules.Users.Domain.Users.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Name")
                        .HasName("pk_roles");

                    b.ToTable("roles", "users");

                    b.HasData(
                        new
                        {
                            Name = "Administrator"
                        },
                        new
                        {
                            Name = "Teacher"
                        },
                        new
                        {
                            Name = "Student"
                        },
                        new
                        {
                            Name = "Editor"
                        });
                });

            modelBuilder.Entity("WorkflowTracking.Modules.Users.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identity_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_name");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("mobile");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", "users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.Property<string>("PermissionCode")
                        .HasColumnType("character varying(100)")
                        .HasColumnName("permission_code");

                    b.Property<string>("RoleName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("PermissionCode", "RoleName")
                        .HasName("pk_role_permissions");

                    b.HasIndex("RoleName")
                        .HasDatabaseName("ix_role_permissions_role_name");

                    b.ToTable("role_permissions", "users");

                    b.HasData(
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "users:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "classrooms:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "classrooms:create",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "classrooms:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "classrooms:delete",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "classrooms:add-student",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "classrooms:remove-student",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "students:invite",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "attendance:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "attendance:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "attendance:record",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "qr:generate",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "spiritual:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "roles:read",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "roles:update",
                            RoleName = "Administrator"
                        },
                        new
                        {
                            PermissionCode = "classrooms:read",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "classrooms:create",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "classrooms:update",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "classrooms:delete",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "classrooms:add-student",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "classrooms:remove-student",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "students:invite",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "attendance:read",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "attendance:update",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "attendance:record",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "qr:generate",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "qr:scan",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "spiritual:read",
                            RoleName = "Teacher"
                        },
                        new
                        {
                            PermissionCode = "users:read",
                            RoleName = "Student"
                        },
                        new
                        {
                            PermissionCode = "users:update",
                            RoleName = "Student"
                        },
                        new
                        {
                            PermissionCode = "attendance:read",
                            RoleName = "Student"
                        },
                        new
                        {
                            PermissionCode = "attendance:record",
                            RoleName = "Student"
                        },
                        new
                        {
                            PermissionCode = "qr:scan",
                            RoleName = "Student"
                        },
                        new
                        {
                            PermissionCode = "spiritual:read",
                            RoleName = "Student"
                        },
                        new
                        {
                            PermissionCode = "spiritual:record",
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<string>("RolesName")
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("RolesName", "UserId")
                        .HasName("pk_user_roles");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", "users");
                });

            modelBuilder.Entity("PermissionRole", b =>
                {
                    b.HasOne("WorkflowTracking.Modules.Users.Domain.Users.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("WorkflowTracking.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_name");
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("WorkflowTracking.Modules.Users.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_roles_name");

                    b.HasOne("WorkflowTracking.Modules.Users.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
